version: '3.8'

services:
  web:
    build: .
    # Имя для создаваемого контейнера
    container_name: backend-fastapi
    command: uvicorn main:app --host 0.0.0.0 --port 8003 --reload
    environment:
      - PYTHONUNBUFFERED=True
    # Перезапускаем сервис в случае падения
    restart: on-failure
    volumes:
      - .:/usr/src/app/
    ports:
      - "8003:8003"